default_platform(:ios)

platform :ios do
  desc "Build app for release"
  lane :build do
    build_app(scheme: "hospitalManager")
  end

  desc "Push to TestFlight"
  lane :release do
    build_app(scheme: "hospitalManager")
    upload_to_testflight
  end
end
